# Generated by Django 6.0.1 on 2026-01-08 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamEcrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_exam_ecrit', models.IntegerField(unique=True)),
                ('description_exam_ecrit', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamOrale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_exam_orale', models.IntegerField(unique=True)),
                ('description_exam_orale', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionEcrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_qst', models.IntegerField()),
                ('image_qst', models.TextField(blank=True, help_text='Base64 encoded image', null=True)),
                ('text_qst', models.TextField()),
                ('choice_a', models.TextField(default='Option A')),
                ('choice_b', models.TextField(default='Option B')),
                ('choice_c', models.TextField(default='Option C')),
                ('choice_d', models.TextField(default='Option D')),
                ('solution_qst', models.TextField()),
                ('score', models.IntegerField(default=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='revision.examecrit')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOrale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_qst', models.IntegerField()),
                ('image_qst', models.TextField(blank=True, help_text='Base64 encoded image', null=True)),
                ('audio_url', models.URLField(blank=True, help_text='URL to audio file (CDN)', null=True)),
                ('text_qst', models.TextField()),
                ('choice_a', models.TextField(default='Option A')),
                ('choice_b', models.TextField(default='Option B')),
                ('choice_c', models.TextField(default='Option C')),
                ('choice_d', models.TextField(default='Option D')),
                ('solution_qst', models.TextField()),
                ('score', models.IntegerField(default=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='revision.examorale')),
            ],
        ),
    ]
