# Generated by Django 6.0.1 on 2026-01-07 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamOrale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_exam_orale', models.IntegerField(unique=True)),
                ('description_exam_orale', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOrale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_qst', models.IntegerField()),
                ('image_qst', models.TextField(blank=True, help_text='Base64 encoded image', null=True)),
                ('audio_qst', models.TextField(blank=True, help_text='Base64 encoded audio', null=True)),
                ('text_qst', models.TextField()),
                ('solution_qst', models.TextField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='revision.examorale')),
            ],
        ),
    ]
