# Generated by Django 6.0.1 on 2026-01-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionorale',
            name='choice_a',
            field=models.TextField(default='Option A'),
        ),
        migrations.AddField(
            model_name='questionorale',
            name='choice_b',
            field=models.TextField(default='Option B'),
        ),
        migrations.AddField(
            model_name='questionorale',
            name='choice_c',
            field=models.TextField(default='Option C'),
        ),
        migrations.AddField(
            model_name='questionorale',
            name='choice_d',
            field=models.TextField(default='Option D'),
        ),
    ]
