# Generated by Django 6.0.1 on 2026-01-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0002_questionorale_choice_a_questionorale_choice_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionorale',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
